export class Domain{
    domainId : number;
    applicationNo : string;
    user : string;
    userMailId : string;
    bankName : string;
    domainName : string;
    numberOfYears : number;
    cost : number;
    organizationName : string;
    registrationDate : Date;
    renewalDate : Date;
    status : string;
    industry : string;
    nsRecordStatus : string;
    submissionDate : Date;
    nameServerIds : string;
    organisationId : number;
    paymentStatus : string;
}